Repository Penguinification/dd2480-DECIDE, pull requests merged in 2023-01, with the labels that each got.

#2 Create entry point
  main.py
Labels: enhancement

#19 Implement lic_0
  cmv.py
  test_cmv.py
Labels: enhancement

#20 Implement lic_3
  cmv.py
  test_cmv.py
Labels: enhancement

#21 Implement lic_2
  cmv.py
  test_cmv.py
Labels: enhancement

#23 Make epsilon < pi
  test_cmv.py
Labels: invalid

#24 Implement lic_4
  cmv.py
  test_cmv.py
Labels: enhancement

#25 Implement lic_1
  cmv.py
  test_cmv.py
Labels: enhancement

#26 Implement lic_5
  cmv.py
  test_cmv.py
Labels: enhancement

#27 Implement lic_6
  cmv.py
  test_cmv.py
Labels: enhancement

#29 Implement lic_7
  cmv.py
  test_cmv.py
Labels: enhancement

#30 Add and implement pum function
  pum.py
  test_pum.py
Labels: enhancement

#33 Add and implement launch
  launch.py
  test_launch.py
Labels: enhancement

#34 Implement fuv function
  fuv.py
  test_fuv.py
Labels: enhancement

#38 Add input validation
  main.py
  test_main.py
Labels: enhancement

#39 Update README
  README.md
Labels: documentation

#42 Implement lic_13
  cmv.py
  test_cmv.py
Labels: enhancement
